apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= NAME %>
spec:
  selector:
    matchLabels:
      foo: <%= LABELS.foo %>
      bar: <%= LABELS.bar %>
  replicas: 1
  template:
    metadata:
      labels:
        foo: <%= LABELS.foo %>
        bar: <%= LABELS.bar %>
    spec:
      containers:

        - name: web
          imagePullPolicy: Always
          image: "tutum/hello-world:<%= VERSION %>"
          ports:
            - containerPort: 80           
