apiVersion: v1
kind: Service
metadata:
  name: <%= NAME %>
  labels:
    foo: <%= LABELS.foo %>
    bar: <%= LABELS.bar %>
    version: <%= version %>
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    foo: <%= LABELS.foo %>
    bar: <%= LABELS.bar %>
    version: <%= VERSION %>
